"""empty message

Revision ID: 6007a0d57816
Revises: 71503b29c05a
Create Date: 2018-05-18 22:45:46.690324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6007a0d57816'
down_revision = '71503b29c05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('deleted', sa.Enum('Y', 'N', name='yesorno'), nullable=True))
    op.add_column('articles', sa.Column('reported', sa.Enum('Y', 'N', name='yesorno'), nullable=True))
    op.drop_column('articles', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('status', mysql.ENUM('USE', 'DELETED', 'REPORTED'), nullable=True))
    op.drop_column('articles', 'reported')
    op.drop_column('articles', 'deleted')
    # ### end Alembic commands ###
