"""user token nonce

Revision ID: 71503b29c05a
Revises: aac9a548d9f5
Create Date: 2018-05-04 13:42:42.222974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71503b29c05a'
down_revision = 'aac9a548d9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('nonce', sa.String(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'nonce')
    # ### end Alembic commands ###
