"""user token is_issued

Revision ID: aac9a548d9f5
Revises: f7acbb65b224
Create Date: 2018-05-04 11:39:23.073618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac9a548d9f5'
down_revision = 'f7acbb65b224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('is_issued', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'is_issued')
    # ### end Alembic commands ###
